### ISSUE TITLE
Plugin installé, pas de rendu

### ISSUE THREAD

**Issue by zuperninja** [takion/zome-polar-rhombizonahedron#1]
Salut !

Ton plugin a l'air top, je suis sur sketch up 2017, j'arrive à l'installer, mais quand je vais dans le menu extension et je choisi mes paramètres, rien ne se modélise.

Est-ce que j'ai loupé une étape ?

Merci !

**Comment by devthejo** [comment]
Salut,

il était codé pour Google Sketchup 8,
je viens de le mettre à jour à l'instant en testant sur Trimble 2016 (pour le moment le 2017 ne passe pas sur mon Linux).

Après l'avoir réinstallé il ne faut pas oublier de fermer et ré-ouvrir sketchup.

Je veux bien ton retour pour savoir si il fonctionne correctement sur Sketchup 2017

Merci

**Comment by devthejo** [comment]
thanks @zuperninja
[https://github.com/zuperninja/blog/issues/1](https://github.com/zuperninja/blog/issues/1)

**Comment by zuperninja** [comment]
Marche nickel sur 2016 et 2017. Tu peux reprendre ce que j'ai écris pour un readme :) Je vais regarder si je peux le traduire

**Comment by devthejo** [comment]
OK super cool, merci !

Tu peux faire un fork, le cloner sur ta machine,
comme ça tu peux rajouter le readme.md,
une traduction ou toute autre contribution,
ensuite tu push sur ton fork,
et à chaque fois que tu veux que j'intègre tes contributions tu fais une pull request sur github,
et comme ça je peux valider et intégrer ton apport en un click ;)

Après, si t'as pas le temps ou l'envie d'utiliser le workflow de git, j'intégrerai moi même tes contributions, as you wish.

**Comment by devthejo** [comment]
Le redémarrage n'est nécessaire en cas d'installation à neuf, c'était uniquement dans le cas d'une réinstallation, j'ai oublié de préciser.
